### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by viaahmed** [qiweiii/markdown-sticky-notes#10]

**Comment by viaahmed** [comment]
BTW, thanks

**Comment by qiweiii** [comment]
> BTW, thanks

Hi @viaahmed, could u please provide a bit describtion of the problem, I will definitely try to fix it.

**Comment by viaahmed** [comment]
I surely return back to you later

**Comment by viaahmed** [comment]
I expected that extension will pop up on click, but nothing happened.

**Comment by viaahmed** [comment]
Update: it worked on #10 this tab. But it is not working in Google Meet.

**Comment by qiweiii** [comment]
@viaahmed Thanks for update, I will look into it.

**Comment by viaahmed** [comment]
Update: I tried again after a reload, it worked this time thanks.
