### ISSUE TITLE
Blurry Editor

### ISSUE THREAD

**Issue by viaahmed** [qiweiii/markdown-sticky-notes#11]
The Editor is Blurry, but output is clear.

**Comment by qiweiii** [comment]
@viaahmed which website?

**Comment by viaahmed** [comment]
@qiweii  Everywhere. The text is blurry.

I think it is a universal problem, it also happens in Obsidian.md

So, the developers there use some CSS rule to make it legible...

**Comment by qiweiii** [comment]
Could you show me a screenshot of the blurry editor? It will be very helpful

If it's everywhere, I guess it could be CSS conflict with some other extension's style in your browser. But it's my extension's problem, I will have to solve CSS encapsulation, maybe that will fix blurry editor.

**Comment by viaahmed** [comment]
@qiweiii

I think it a temporary issue when we size and resize the note. The `consolas` font may be causing that legibility issue in my PC.

**Comment by viaahmed** [comment]
I used another theme `the-matrix`. Now it is fine.

**Comment by viaahmed** [comment]
![](https://user-images.githubusercontent.com/46238846/103866919-8e9ba100-50ec-11eb-8361-4dc3c9e02d09.png)

**Comment by qiweiii** [comment]
I think it's not blurry haha, you may go to setting page and change the font theme to the-matrix, it will set the default theme to  the-matrix.

**Comment by viaahmed** [comment]
Got it.
