### ISSUE TITLE
Is there any shortcut to quickly open note?

### ISSUE THREAD

**Issue by viaahmed** [qiweiii/markdown-sticky-notes#17]
@qiweiii I found there is no option to configure any shortcut.

**Comment by qiweiii** [comment]
There is no shortcut now, but I will add it in the next publish

**Comment by qiweiii** [comment]
> @qiweiii I found there is no option to configure any shortcut.

I found that you could set your own shortcut in [chrome://extensions/shortcuts](chrome://extensions/shortcuts)
