### ISSUE TITLE
Feature Request: Math rendering

### ISSUE THREAD

**Issue by samankittani** [qiweiii/markdown-sticky-notes#49]
This feels like a big ask, But basic math rendering would be a welcome feature, similar to github's functionality.

$\frac{1}{2} * \pi$

**Comment by qiweiii** [comment]
Nice suggestions!

I submited a new version to support math, you will be able to see it in a few days after the extension is reviewed and published by Chrome/Firefox web store

**Comment by samankittani** [comment]
Wonderful!
